from __future__ import annotations

from pathlib import Path

from .security import EgressPolicy

TEXT_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".kt", ".kts", ".go", ".rs",
    ".c", ".h", ".cpp", ".hpp", ".sh", ".bash", ".zsh", ".sql", ".yml", ".yaml",
    ".json", ".md", ".markdown", ".txt", ".toml", ".ini", ".cfg", ".conf", ".xml",
    ".rexx", ".rex", ".jcl", ".proc", ".cob", ".cbl", ".cobol", ".pli", ".pl1",
}
ARCHIVE_EXTENSIONS = {".jar", ".war", ".ear", ".zip", ".7z", ".rar", ".tar", ".tgz", ".gz", ".bz2", ".xz"}
COMPILED_EXTENSIONS = {".class", ".pyc", ".pyo", ".o", ".obj", ".a", ".lib", ".so", ".dylib", ".dll", ".exe"}
GENERATED_MARKERS = ("generated by", "auto-generated", "autogenerated", "do not edit", "@generated", "generated source")
MAX_TEXT_FILE_BYTES = 2 * 1024 * 1024
MAX_PDF_FILE_BYTES = 50 * 1024 * 1024
GENERATED_LARGE_BYTES = 200 * 1024
MINIFIED_LINE_CHARS = 20_000
INDEX_POLICY_VERSION = 2  # v0.6.7.4 balanced credential handling

# Directories that are never useful as project knowledge when walking a
# non-Git source. Git-backed sources use ``git ls-files`` instead.
SKIP_DIRS = {
    ".git", ".venv", "venv", "node_modules", "dist", "build", "target",
    ".next", ".idea", ".vscode", "chroma", "__pycache__",
}


def should_skip_dir(name: str) -> bool:
    return name in SKIP_DIRS


class FileEligibilityPolicy:
    """Classifies source files before local parsing or remote embedding.

    The policy is intentionally conservative for enterprise source repositories:
    archives/compiled artefacts and machine-generated/minified payloads are not
    useful RAG input and can also upset provider-side embedding validation.
    """

    def __init__(self, egress: EgressPolicy | None = None):
        self.egress = egress or EgressPolicy()

    @staticmethod
    def supported(path: Path) -> bool:
        return path.name == "PROJECT.md" or path.suffix.lower() in TEXT_EXTENSIONS | {".pdf"}

    def classify(self, path: Path) -> tuple[bool, str | None]:
        suffix = path.suffix.lower()
        if suffix in ARCHIVE_EXTENSIONS:
            return False, "archive"
        if suffix in COMPILED_EXTENSIONS:
            return False, "compiled-binary"
        if not self.egress.path_allowed(path):
            return False, "sensitive-path"
        if not self.supported(path):
            return False, "unsupported-type"
        try:
            size = path.stat().st_size
        except OSError:
            return False, "unreadable"
        if suffix == ".pdf":
            return (False, "oversized-pdf") if size > MAX_PDF_FILE_BYTES else (True, None)
        if size > MAX_TEXT_FILE_BYTES:
            return False, "oversized-text"
        try:
            with path.open("rb") as fh:
                sample = fh.read(min(size, 512 * 1024))
        except OSError:
            return False, "unreadable"
        if b"\x00" in sample:
            return False, "binary-content"
        text = sample.decode("utf-8", errors="replace")
        lower = text.lower()
        if size >= GENERATED_LARGE_BYTES and any(marker in lower[:32_000] for marker in GENERATED_MARKERS):
            return False, "generated-large-source"
        if size >= 64 * 1024:
            longest = max((len(line) for line in text.splitlines()), default=0)
            if longest >= MINIFIED_LINE_CHARS:
                return False, "minified-or-long-line"
        return True, None
